import json

ARG_CONFIGS = json.load(open("configs/args_config.json", "r"))
DESCRIPTION  = ARG_CONFIGS["description"]
ARGUMENTS = ARG_CONFIGS["arguments"]

BASE_MODEL_CONFIG = json.load(open("configs/base_model_config.json", "r"))
SYSTEM_PROMPT_FILE = BASE_MODEL_CONFIG["SYSTEM_PROMPT_FILE"]
BASE_SYSTEM_PROMPT = open(SYSTEM_PROMPT_FILE, "r").read()
REFERENCE_INSTRUCTIONS_FILE = BASE_MODEL_CONFIG["REFERENCE_INSTRUCTIONS_FILE"]
REFERENCE_INSTRUCTIONS = open(REFERENCE_INSTRUCTIONS_FILE, "r").read()

STM_CONFIG = json.load(open("configs/stm_config.json", "r"))
SUMMARIZATION_MODEL = STM_CONFIG["SUMMARIZATION_MODEL"]
CONTEXT_SIZING = STM_CONFIG["CONTEXT_SIZING"]
SUMMARIZATION_PROMPT_FILE = SUMMARIZATION_MODEL["SYSTEM_PROMPT_FILE"]
SUMMARIZATION_PROMPT = open(SUMMARIZATION_PROMPT_FILE, "r").read()

TOOL_CONFIGS = json.load(open("configs/tool_config.json"))
TXT_TOOL_DESCRIPTIONS = TOOL_CONFIGS["TXTTools"]["functions"]
TXT_TOOL_READ_ARGS = TOOL_CONFIGS["TXTTools"]["read_args"]
TXT_TOOL_WRITE_ARGS = TOOL_CONFIGS["TXTTools"]["write_args"]
SEARCH_ARGS = TOOL_CONFIGS["TraversalTools"]["search_args"]
FUNCTION_DESCRIPTION = TOOL_CONFIGS["TraversalTools"]["functions"]
CSV_TOOL_DESCRIPTIONS = TOOL_CONFIGS["CSVTools"]["functions"]
DIRECTORY_TOOL_DESCRIPTIONS = TOOL_CONFIGS["DirectoryTools"]["functions"]
